--- # EC2 New VPC Network

- hosts: local
  connection: local
  remote_user: centos
  become: yes
  tasks:
  - name: ec2 vpc net
    ec2_vpc_net:
      name: Dev
      state: present
      cidr_block: 10.10.10.0/24
    register: vpc
  - debug: var=vpc       
